### ISSUE TITLE
Can we (and should we?) guaruntee that spread stack items will be evenly sized?

### ISSUE THREAD

**Issue by byronhulcher** [meetup/sassquatch2#49]
If I have two `.stack-item`s which are spread at a certain media size, I'd like the ability to guaruntee they will be evenly sized, regardless of their content.  This way, if I have two `.stack`s on top of each other containing the same number of children, I'd like to set a way for the elements to line their gutters up.

**Comment by akdetrick** [comment]
![screen shot 2015-03-16 at 5 53 25 pm_thumb](https://cloud.githubusercontent.com/assets/231252/6692389/cdcd869c-cca2-11e4-9916-8a5c347c2a50.png)

It's difficult to bake a `flex-basis` for any `stack-item` or `row-item` in the framework, because a `stack` or `row` can contain any number of items.

This is one of the few cases where I think the solution is to turn to writing some custom css in a page-specific partial in order to define a flex-basis.

Assuming that the stack elements in the above screenshot spread at the `medium` breakpoint and the ideal with of the items is `400px`, the solution would look something like this:

```scss
@include atMediaUp(medium) {
	.stack-item--myCustomVariant {
		@include flex-basis(400px);
	}
}
```

**Comment by byronhulcher** [comment]
Going to go with:
```
@include atMediaUp(medium) {
    .atMedium_stack--spread-2-column > .stack-item {
        @include flex-basis(400px);
    }
}
```
I think it would make sense that I attach this to the same element I declare stack--spread on

**Comment by akdetrick** [comment]
:+1:
